name: codacy-coverage-reporter

on:
  push:
    branches:
      - main
        CODACY
  pull_request:
    branches:
      - main
        CODACY
        
jobs:
  codacy-coverage-reporter:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
