name: CodeFresh

on:
  push:
    branches: [ "main", "CodeFresh" ]
  pull_request:
    branches: [ "main", "CodeFresh" ]

permissions: read-all

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
    - name: report image
      with:
        # Name of runtime to implement the enrichment
        CF_RUNTIME_NAME: 'codefresh-hosted'

        # Codefresh API key !! Committing a plain text token is a security risk. We highly recommend using an encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_API_KEY: ${{ secrets.CF_TOKEN }}

        # The git branch which is related for the commit
        CF_GIT_BRANCH: '${{ github.ref_name }}'

        # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using an encrypted secrets. !!
        # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
        CF_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Name of Issue Tracking integration
        CF_ISSUE_TRACKING_INTEGRATION: 'eti-jira'

        # Jira project filter
        CF_JIRA_PROJECT_PREFIX: 'KAN'

        # String starting with the issue ID to associate with image
        CF_JIRA_MESSAGE: 'KAN-1'

      uses: codefresh-io/codefresh-report-image@latest
