name: DeepSource

on:
  push:
    branches:
      - main
        deepsource
  pull_request:
    branches:
      - main
        deepsource

jobs:
  deepsource:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Report test coverage to DeepSource
      uses: deepsourcelabs/test-coverage-action@master
      with:
        key: csharp
        coverage-file: coverage.xml
        dsn: ${{ secrets.DEEPSOURCE_DSN }}
    - name: Report results to DeepSource
      run: |
      # Tests have finished and a test coverage report is available

      # Install deepsource CLI
        curl https://deepsource.io/cli | sh

      # From the root directory, run the report coverage command
        ./bin/deepsource report --analyzer test-coverage --key csharp --value-file ./path/to/report

      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
