name: DeepSource

on:
  push:
    branches:
      - main
        deepsource
  pull_request:
    branches:
      - main
        deepsource

jobs:
  deepsource:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Report test coverage to DeepSource
      uses: deepsourcelabs/test-coverage-action@master
      with:
        key: csharp
        coverage-file: coverage.xml
        dsn: ${{ secrets.DEEPSOURCE_DSN }}
