on:
  push:
    branches:
      - master
      - Honeybadger
  pull_request:
    branches:
      - master

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: honeybadger-io/github-notify-deploy-action@v1
      with:
        api_key: ${{ secrets.HONEYBADGER_API_KEY }}
