name: Snyk Ubuntu
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Snyk
      uses: snyk/actions/setup@master
        
    - name: Snyk monitor
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
