name: Snyk Mac OS
on: push
jobs:
  security:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup coreutils
      run: sudo install coreutils

    - name: Setup Snyk
      uses: snyk/actions/setup@master
        
    - name: Snyk monitor
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
