name: Testspace Action
on:
  push:
    branches: [main, coveralls]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [main, coveralls]
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions: read-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}
          token: ${{ secrets.TESTSPACE_TOKEN }}
      - name: Testspace push test content
        run: testspace [${{ matrix.os}}]./testcontent/*.xml
      - name: Testspace Setup CLI
        uses: testspace-com/setup-testspace@v1.0.6
        with:
          domain: ${{github.repository_owner}}
          token: ${{ secrets.TESTSPACE_TOKEN }}
