name: Testspace Action
on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions: read-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Testspace client install & config
        uses: testspace-com/setup-testspace@ee1482f978eb5010ec27b6f6372904f01f2edd68 # v1.0.6
        with:
          domain: ${{ github.repository_owner }}
          token: ${{ secrets.TESTSPACE_TOKEN }}
      - name: Testspace push test content
        run: testspace [${{ matrix.os}}]./testcontent/*.xml
      - name: Testspace Setup CLI
        uses: testspace-com/setup-testspace@ee1482f978eb5010ec27b6f6372904f01f2edd68 # v1.0.6.0.6
        with:
          domain: ${{github.repository_owner}}
          token: ${{ secrets.TESTSPACE_TOKEN }}
